// <auto-generated />
using System;
using CSharp_intro_1.Common.Repository.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharp_intro_1.Common.Repository.DataAccess.Migrations
{
    [DbContext(typeof(AppContexts))]
    [Migration("20230308130452_AddBucketPhotoToBucketTable")]
    partial class AddBucketPhotoToBucketTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CSharp_intro_1.People.Repositories.Modal.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NewId()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d22bd9ba-27ca-4271-b9fb-f68b356f06f3"),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("d12bd9ba-27ca-4271-b9fb-f68b356f06f3"),
                            FirstName = "Will",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("CSharp_intro_1.Repositories.Models.Bucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NewId()");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalTasks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bucket", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b29fc40-ca47-1067-b31d-00dd010662da"),
                            Title = "My DB Bucket"
                        });
                });

            modelBuilder.Entity("CSharp_intro_1.Repositories.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NewId()");

                    b.Property<Guid?>("BucketId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PersonId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BucketId");

                    b.HasIndex("PersonId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d42bd8ba-27ca-4271-b9fb-f68b356f06f2"),
                            BucketId = new Guid("6b29fc40-ca47-1067-b31d-00dd010662da"),
                            Description = "custom software solution for x company",
                            PersonId = new Guid("d22bd9ba-27ca-4271-b9fb-f68b356f06f3"),
                            Priority = 0,
                            Status = 0,
                            Title = "Development work"
                        },
                        new
                        {
                            Id = new Guid("d21bd8ba-27ca-4271-b9fb-f68b356f06f3"),
                            BucketId = new Guid("6b29fc40-ca47-1067-b31d-00dd010662da"),
                            Description = "promotion material for new software",
                            PersonId = new Guid("d22bd9ba-27ca-4271-b9fb-f68b356f06f3"),
                            Priority = 0,
                            Status = 1,
                            Title = "Marketing work"
                        });
                });

            modelBuilder.Entity("CSharp_intro_1.Repositories.Models.Task", b =>
                {
                    b.HasOne("CSharp_intro_1.Repositories.Models.Bucket", "Bucket")
                        .WithMany("Tasks")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharp_intro_1.People.Repositories.Modal.Person", "Person")
                        .WithMany("Tasks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bucket");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CSharp_intro_1.People.Repositories.Modal.Person", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CSharp_intro_1.Repositories.Models.Bucket", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
